"""
This is configuration file containing dictionary for grbl codes to its name
"""
grbl_config = {
    "step_pulse_us": "$0",
    "step_delay_ms": "$1",
    "step_invert_mask": "$2",
    "dir_invert_mask": "$3",
    "step_en_invert_mask": "$4",
    "limit_pins_invert_mask": "$5",
    "probe_pin_invert_mask": "$6",
    "status_report_mask": "$10",
    "junction_deviation": "$11",
    "arc_tolerance": "$12",
    "report_inches": "$13",
    "soft_limits_en": "$20",
    "hard_limits_en": "$21",
    "homing_cycle_en": "$22",
    "homing_cycle_dir": "$23",
    "homing_feed": "$24",
    "homing_seek": "$25",
    "homing_debounce": "$26",
    "homing_pulloff": "$27",
    "max_spindle_rpm": "$30",
    "min_spindle_rpm": "$31",
    "laser_mode": "$32",
    "x_steps_mm": "$100",
    "y_steps_mm": "$101",
    "z_steps_mm": "$102",
    "x_rate_mm_min": "$110",
    "y_rate_mm_min": "$111",
    "z_rate_mm_min": "$112",
    "x_acc_mm_sec": "$120",
    "y_acc_mm_sec": "$121",
    "z_acc_mm_sec": "$122",
    "x_max_travel": "$130",
    "y_max_travel": "$131",
    "z_max_travel": "$132",
}
